### ISSUE TITLE
Generated JS breaks when selector specified on multiple lines

### ISSUE THREAD

**Issue by vsr** [vsr/css-to-js#1]
```css
.a,
.b {
  color: red;
}
```
JS generated for above css breaks since selectors are split across multiple lines.
